### ISSUE TITLE
Issue: "error: no provider registered with name digitalocean, do you need to add a gem to your Gemfile?"

### ISSUE THREAD

**Issue by talk2MeGooseman** [getkuby/kuby-core#19]
Hello,

I tried to give Kuby a try on a newly generated Rails application today but came across an issue when trying to run build and also trying to start my server locally.

I generated my Kuby config using the generator command and also added `config/initializer/kuby.rb`. I then setup everything to deploy to Azure.

Versions being used:
macOS 10.15.7
Ruby 2.5.8
Rails 6.0.3.4
kuby-core 0.11.1
kuby-azure 0.3.0

After setting up my kuby.rb file at the root of my project I attempted to build the image and was greeted with the following.
```
> kuby -e production build
error: no provider registered with name azure, do you need to add a gem to your Gemfile?
```

Also when attempting the run `rails s` I also received the following error

```
❯ rails s
=> Booting Puma
=> Rails 6.0.3.4 application starting in development
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	93: from bin/rails:4:in `<main>'
	92: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	91: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	90: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	89: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	88: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	87: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	86: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	85: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	84: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<top (required)>'
	83: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
	82: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
	81: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	80: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	79: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	78: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `perform'
	77: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `tap'
	76: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	75: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:37:in `start'
	74: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	73: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	72: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	71: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	70: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	69: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	68: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	67: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	66: from config.ru:3:in `block in <main>'
	65: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	64: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	63: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	62: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	61: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
	60: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	59: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	58: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	57: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	56: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	55: from /Users/erikguzman/Documents/code/HelloKuby/config/environment.rb:5:in `<top (required)>'
	54: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
	53: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
	52: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	51: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	50: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	49: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:347:in `call'
	48: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:347:in `each'
	47: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	46: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	45: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:415:in `call'
	44: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `tsort_each_child'
	43: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `each'
	42: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	41: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	40: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	39: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	38: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	37: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	36: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
	35: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
	34: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `block in <class:Engine>'
	33: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `each'
	32: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
	31: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/engine.rb:665:in `load_config_initializer'
	30: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/notifications.rb:182:in `instrument'
	29: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/engine.rb:666:in `block in load_config_initializer'
	28: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
	27: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	26: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'
# aws:
	25: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	24: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	23: from /Users/erikguzman/Documents/code/HelloKuby/config/initializers/kuby.rb:2:in `<top (required)>'
	22: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/kuby-core-0.11.1/lib/kuby.rb:46:in `load!'
	21: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	20: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	19: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	18: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
	17: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	16: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	15: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	14: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	13: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	12: from /Users/erikguzman/Documents/code/HelloKuby/kuby.rb:5:in `<top (required)>'
	11: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/kuby-core-0.11.1/lib/kuby.rb:53:in `define'
	10: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/kuby-core-0.11.1/lib/kuby.rb:53:in `instance_eval'
	 9: from /Users/erikguzman/Documents/code/HelloKuby/kuby.rb:7:in `block in <top (required)>'
	 8: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/kuby-core-0.11.1/lib/kuby/definition.rb:16:in `environment'
	 7: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/kuby-core-0.11.1/lib/kuby/definition.rb:16:in `instance_eval'
	 6: from /Users/erikguzman/Documents/code/HelloKuby/kuby.rb:34:in `block (2 levels) in <top (required)>'
	 5: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/kuby-core-0.11.1/lib/kuby/environment.rb:27:in `kubernetes'
	 4: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/kuby-core-0.11.1/lib/kuby/environment.rb:27:in `instance_eval'
	 3: from /Users/erikguzman/Documents/code/HelloKuby/kuby.rb:72:in `block (3 levels) in <top (required)>'
	 2: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/kuby-core-0.11.1/lib/kuby/kubernetes/spec.rb:23:in `provider'
	 1: from /Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/kuby-azure-0.3.0/lib/kuby/azure/provider.rb:13:in `configure'
/Users/erikguzman/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/kuby-azure-0.3.0/lib/kuby/azure/provider.rb:13:in `instance_eval': wrong number of arguments (given 0, expected 1..3) (ArgumentError)
```

The example project code is here: https://github.com/talk2MeGooseman/HelloKuby

Any help is appreciated because I would love to try this out.

**Comment by gentlemich** [comment]
Getting the same issue with [eks](https://github.com/getkuby/kuby-eks/issues/1)

**Comment by camertron** [comment]
Hey @talk2MeGooseman, let's see if we can figure this out.

First, it looks like bundler isn't automatically requiring kuby-azure for some reason. Try adding `require 'kuby/azure'` to the top of your kuby.rb. Second, it looks like you forgot to remove `provider :docker_desktop`. Try removing that line and try again :)

**Comment by camertron** [comment]
The `require` issue has come up twice now, so I'm going to tweak the error message to make it clearer what needs to be done. The `provider` issue is a little trickier and has to do with how providers are configured internally.

**Comment by camertron** [comment]
Hey @talk2MeGooseman, are you still experiencing this problem? If not, I'd like to close this issue.

**Comment by talk2MeGooseman** [comment]
@camertron  Ill get back to you shortly, I need to set up everything again to re-test it since the computer I was developing off of decided to not work anymore 😅

**Comment by talk2MeGooseman** [comment]
Looks like that did the trick, Github Codespace to the rescue for me. 

One super trivial note for potential better error messaging. I was using a simple Rails using SQLite and accidentally also left in the database connection code in and go this not so detailed error, maybe an opportunity to provide better error messaging here just in case?
```NoMethodError: undefined method `user' for #<Kuby::Plugins::RailsApp::Sqlite:0x0000564b1398f990>
/home/codespace/workspace/HelloKuby/kuby.rb:61:in `block (5 levels) in <top (required)>'```

**Comment by camertron** [comment]
Awesome, glad you got it working! Ok, let me see what I can do about improving that error message, thanks for the feedback :)
