### ISSUE TITLE
Sorbet sig in anonymous module potentially breaks CLI

### ISSUE THREAD

**Issue by lazyatom** [getkuby/kuby-core#23]
I think [this line](https://github.com/getkuby/kuby-core/blob/d3e6b6e12038d2464cf533af65c434391ad5bf5f/lib/kuby/commands.rb#L22) might have broken the CLI; when I run `bundle exec kuby -e production build` using 0.11.3, I get the following error:

```
NoMethodError: undefined method `sig' for #<Module:0x00007f9bb6427198>
  /Users/james/.gem/ruby/2.6.5/gems/kuby-core-0.11.3/lib/kuby/commands.rb:22:in `block in <class:Commands>'
  /Users/james/.gem/ruby/2.6.5/gems/kuby-core-0.11.3/lib/kuby/commands.rb:21:in `initialize'
  /Users/james/.gem/ruby/2.6.5/gems/kuby-core-0.11.3/lib/kuby/commands.rb:21:in `new'
  /Users/james/.gem/ruby/2.6.5/gems/kuby-core-0.11.3/lib/kuby/commands.rb:21:in `<class:Commands>'
  /Users/james/.gem/ruby/2.6.5/gems/kuby-core-0.11.3/lib/kuby/commands.rb:7:in `<module:Kuby>'
  /Users/james/.gem/ruby/2.6.5/gems/kuby-core-0.11.3/lib/kuby/commands.rb:6:in `<top (required)>'
  /Users/james/.gem/ruby/2.6.5/gems/kuby-core-0.11.3/bin/kuby:4:in `require'
  /Users/james/.gem/ruby/2.6.5/gems/kuby-core-0.11.3/bin/kuby:4:in `<top (required)>'
  /Users/james/.gem/ruby/2.6.5/bin/kuby:23:in `load'
  /Users/james/.gem/ruby/2.6.5/bin/kuby:23:in `<top (required)>'
```

Possible you need to add an explicit `extend T::Sig` just before this line?

**Comment by camertron** [comment]
Oof, thanks @lazyatom. Fixed and released as v0.11.4.
