### ISSUE TITLE
undefined method `credentials' and undefined method `sig'

### ISSUE THREAD

**Issue by rudolfaraya** [getkuby/kuby-core#25]
I have this problem when configuring kuby with linode

[My repository - Branch](https://github.com/rudolfaraya/last-ubication-vehicle/tree/feature/kuby-deployment)

```ruby
# Gemfile
# Kuby Deployment
gem 'kuby-core', '~> 0.11'
gem 'kuby-linode', '< 1.0'
```
I already verified that the docker credentials and the kubernetes cluster are read correctly

```ruby
# log rails server
undefined method `credentials' for #<Kuby::Docker::DevSpec:0x000055b4c3076840>
/app/kuby.rb:15:in `block (3 levels) in <top (required)>'
/usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/lib/kuby/environment.rb:21:in `instance_eval'
/usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/lib/kuby/environment.rb:21:in `docker'
/app/kuby.rb:14:in `block (2 levels) in <top (required)>'
/usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/lib/kuby/definition.rb:28:in `instance_eval'
/usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/lib/kuby/definition.rb:28:in `environment'
/app/kuby.rb:13:in `block in <top (required)>'
/usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/lib/kuby.rb:53:in `instance_eval'
/usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/lib/kuby.rb:53:in `define'
/app/kuby.rb:5:in `<top (required)>'
/usr/local/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
/usr/local/bundle/ruby/2.5.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/bundle/ruby/2.5.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/bundle/ruby/2.5.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
/usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/lib/kuby.rb:46:in `load!'
/app/config/initializers/kuby.rb:2:in `<top (required)>'
/usr/local/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/usr/local/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/usr/local/bundle/ruby/2.5.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:318:in `block in load'
/usr/local/bundle/ruby/2.5.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/bundle/ruby/2.5.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:318:in `load'
/usr/local/bundle/ruby/2.5.0/gems/railties-6.0.3/lib/rails/engine.rb:666:in `block in load_config_initializer'
/usr/local/bundle/ruby/2.5.0/gems/activesupport-6.0.3/lib/active_support/notifications.rb:182:in `instrument'
/usr/local/bundle/ruby/2.5.0/gems/railties-6.0.3/lib/rails/engine.rb:665:in `load_config_initializer'
/usr/local/bundle/ruby/2.5.0/gems/railties-6.0.3/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/ruby/2.5.0/gems/railties-6.0.3/lib/rails/engine.rb:624:in `each'
/usr/local/bundle/ruby/2.5.0/gems/railties-6.0.3/lib/rails/engine.rb:624:in `block in <class:Engine>'
/usr/local/bundle/ruby/2.5.0/gems/railties-6.0.3/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/ruby/2.5.0/gems/railties-6.0.3/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/ruby/2.5.0/gems/railties-6.0.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/local/bundle/ruby/2.5.0/gems/railties-6.0.3/lib/rails/initializable.rb:50:in `each'
/usr/local/bundle/ruby/2.5.0/gems/railties-6.0.3/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/lib/ruby/2.5.0/tsort.rb:415:in `call'
/usr/local/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/usr/local/bundle/ruby/2.5.0/gems/railties-6.0.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/ruby/2.5.0/gems/railties-6.0.3/lib/rails/application.rb:363:in `initialize!'
/app/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/ruby/2.5.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
/usr/local/bundle/ruby/2.5.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/bundle/ruby/2.5.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/bundle/ruby/2.5.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
/usr/local/bundle/ruby/2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/cli.rb:252:in `boot_system'
/usr/local/bundle/ruby/2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/cli.rb:37:in `run'
/usr/local/bundle/ruby/2.5.0/gems/sidekiq-6.0.7/bin/sidekiq:31:in `<top (required)>'
/usr/local/bundle/ruby/2.5.0/bin/sidekiq:23:in `load'
/usr/local/bundle/ruby/2.5.0/bin/sidekiq:23:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
```
This is my kuby config file:

 ```ruby
# kuby.rb
require 'active_support/core_ext'
require 'active_support/encrypted_configuration'
require 'kuby/linode'

Kuby.define('last-ubication-deploy') do
  app_creds = ActiveSupport::EncryptedConfiguration.new(
      config_path: File.join('config', 'credentials.yml.enc'),
      key_path: File.join('config', 'master.key'),
      env_key: 'RAILS_MASTER_KEY',
      raise_if_missing_key: true
  )

  environment(:development) do
    docker do
      credentials do
        username app_creds[:docker][:username]
        password app_creds[:docker][:password]
        email app_creds[:docker][:email]
      end

      image_url 'docker.io/rudolfaraya/last-ubication-vehicle-app'
    end

    kubernetes do
      provider :linode do
        access_token app_creds[:linode][:access_token]
        cluster_id app_creds[:linode][:cluster_id]
      end

      add_plugin :rails_app do
        database do
          user app_creds[:DATABASE_USER]
          password app_creds[:DATABASE_PASSWORD]
        end
      end
    end
  end
end
```
If I comment out the docker configuration lines, I run this command inside the container and it throws me:

```ruby
/app # bundle exec kuby
bundler: failed to load command: kuby (/usr/local/bundle/ruby/2.5.0/bin/kuby)
NoMethodError: undefined method `sig' for #<Module:0x0000559d0e6c5060>
  /usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/lib/kuby/commands.rb:22:in `block in <class:Commands>'
  /usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/lib/kuby/commands.rb:21:in `initialize'
  /usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/lib/kuby/commands.rb:21:in `new'
  /usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/lib/kuby/commands.rb:21:in `<class:Commands>'
  /usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/lib/kuby/commands.rb:7:in `<module:Kuby>'
  /usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/lib/kuby/commands.rb:6:in `<top (required)>'
  /usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/bin/kuby:4:in `require'
  /usr/local/bundle/ruby/2.5.0/gems/kuby-core-0.11.3/bin/kuby:4:in `<top (required)>'
  /usr/local/bundle/ruby/2.5.0/bin/kuby:23:in `load'
  /usr/local/bundle/ruby/2.5.0/bin/kuby:23:in `<top (required)>'
```
I hope you can help me

**Comment by camertron** [comment]
Hey @rudolfaraya, it looks like there are two things going on here. First, it looks like you've named your deploy environment `:development`. Kuby pre-defines a development deploy environment for local dev that builds Docker images on your local machine and therefore doesn't expect credentials. If you name your environment literally anything else, it should work as expected. I would also suggest upgrading to kuby 0.11.4, released yesterday, to fix the "undefined method" error.

**Comment by rudolfaraya** [comment]
Thanks @camertron. This fixes my errors.
