### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by jwald1** [getkuby/kuby-core#30]
I tried to deploy, but got the following error:

```bash
[FATAL][2020-10-15 18:44:38 -0400]      Deployment/testapp-assets: TIMED OUT (progress deadline: 600s)
[FATAL][2020-10-15 18:44:38 -0400]      Timeout reason: ProgressDeadlineExceeded
[FATAL][2020-10-15 18:44:38 -0400]      Latest ReplicaSet: testapp-assets-86d95fd9c9
[FATAL][2020-10-15 18:44:38 -0400]
[FATAL][2020-10-15 18:44:38 -0400]      The following containers have not passed their readiness probes on at least one pod:
[FATAL][2020-10-15 18:44:38 -0400]      > testapp-assets must respond with a good status code at '/500.html'
[FATAL][2020-10-15 18:44:38 -0400]
[FATAL][2020-10-15 18:44:38 -0400]        - Final status: 1 replica, 1 updatedReplica, 1 unavailableReplica
[FATAL][2020-10-15 18:44:38 -0400]        - Events (common success events excluded):
[FATAL][2020-10-15 18:44:38 -0400]            [Deployment/testapp-assets]     ScalingReplicaSet: Scaled up replica set testapp-assets-86d95fd9c9 to 1 (1 events)
[FATAL][2020-10-15 18:44:38 -0400]            [Pod/testapp-assets-86d95fd9c9-zjmzz]   SuccessfulAttachVolume: AttachVolume.Attach succeeded for volume "pvc-fd6f0799-ee5b-4948-bcb3-1a9acf8c8a1d"  (1 events)
[FATAL][2020-10-15 18:44:38 -0400]            [Pod/testapp-assets-86d95fd9c9-zjmzz]   Unhealthy: Readiness probe failed: HTTP probe failed with statuscode: 404 (99 events)
[FATAL][2020-10-15 18:44:38 -0400]        - Logs from container 'testapp-assets' (last 25 lines shown):
[FATAL][2020-10-15 18:44:38 -0400]            10.244.0.68 - - [15/Oct/2020:22:43:53 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
[FATAL][2020-10-15 18:44:38 -0400]            2020/10/15 22:43:56 [error] 6#6: *184 open() "/usr/share/nginx/assets/current/500.html" failed (2: No such file or directory), client: 10.244.0.68, server: localhost, request: "GET /500.html HTTP/1.1", host: "10.244.0.37:8082"
[FATAL][2020-10-15 18:44:38 -0400]            10.244.0.68 - - [15/Oct/2020:22:43:56 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
[FATAL][2020-10-15 18:44:38 -0400]            2020/10/15 22:43:59 [error] 6#6: *185 open() "/usr/share/nginx/assets/current/500.html" failed (2: No such file or directory), client: 10.244.0.68, server: localhost, request: "GET /500.html HTTP/1.1", host: "10.244.0.37:8082"
[FATAL][2020-10-15 18:44:38 -0400]            10.244.0.68 - - [15/Oct/2020:22:43:59 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
[FATAL][2020-10-15 18:44:38 -0400]            2020/10/15 22:44:02 [error] 6#6: *186 open() "/usr/share/nginx/assets/current/500.html" failed (2: No such file or directory), client: 10.244.0.68, server: localhost, request: "GET /500.html HTTP/1.1", host: "10.244.0.37:8082"
[FATAL][2020-10-15 18:44:38 -0400]            10.244.0.68 - - [15/Oct/2020:22:44:02 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
[FATAL][2020-10-15 18:44:38 -0400]            2020/10/15 22:44:05 [error] 6#6: *187 open() "/usr/share/nginx/assets/current/500.html" failed (2: No such file or directory), client: 10.244.0.68, server: localhost, request: "GET /500.html HTTP/1.1", host: "10.244.0.37:8082"
[FATAL][2020-10-15 18:44:38 -0400]            10.244.0.68 - - [15/Oct/2020:22:44:05 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
[FATAL][2020-10-15 18:44:38 -0400]            2020/10/15 22:44:08 [error] 6#6: *188 open() "/usr/share/nginx/assets/current/500.html" failed (2: No such file or directory), client: 10.244.0.68, server: localhost, request: "GET /500.html HTTP/1.1", host: "10.244.0.37:8082"
[FATAL][2020-10-15 18:44:38 -0400]            10.244.0.68 - - [15/Oct/2020:22:44:08 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
[FATAL][2020-10-15 18:44:38 -0400]            2020/10/15 22:44:11 [error] 6#6: *189 open() "/usr/share/nginx/assets/current/500.html" failed (2: No such file or directory), client: 10.244.0.68, server: localhost, request: "GET /500.html HTTP/1.1", host: "10.244.0.37:8082"
[FATAL][2020-10-15 18:44:38 -0400]            10.244.0.68 - - [15/Oct/2020:22:44:11 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
[FATAL][2020-10-15 18:44:38 -0400]            2020/10/15 22:44:14 [error] 6#6: *190 open() "/usr/share/nginx/assets/current/500.html" failed (2: No such file or directory), client: 10.244.0.68, server: localhost, request: "GET /500.html HTTP/1.1", host: "10.244.0.37:8082"
[FATAL][2020-10-15 18:44:38 -0400]            10.244.0.68 - - [15/Oct/2020:22:44:14 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
[FATAL][2020-10-15 18:44:38 -0400]            2020/10/15 22:44:17 [error] 6#6: *191 open() "/usr/share/nginx/assets/current/500.html" failed (2: No such file or directory), client: 10.244.0.68, server: localhost, request: "GET /500.html HTTP/1.1", host: "10.244.0.37:8082"
[FATAL][2020-10-15 18:44:38 -0400]            10.244.0.68 - - [15/Oct/2020:22:44:17 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
[FATAL][2020-10-15 18:44:38 -0400]            2020/10/15 22:44:20 [error] 6#6: *192 open() "/usr/share/nginx/assets/current/500.html" failed (2: No such file or directory), client: 10.244.0.68, server: localhost, request: "GET /500.html HTTP/1.1", host: "10.244.0.37:8082"
[FATAL][2020-10-15 18:44:38 -0400]            10.244.0.68 - - [15/Oct/2020:22:44:20 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
[FATAL][2020-10-15 18:44:38 -0400]            2020/10/15 22:44:23 [error] 6#6: *193 open() "/usr/share/nginx/assets/current/500.html" failed (2: No such file or directory), client: 10.244.0.68, server: localhost, request: "GET /500.html HTTP/1.1", host: "10.244.0.37:8082"
[FATAL][2020-10-15 18:44:38 -0400]            10.244.0.68 - - [15/Oct/2020:22:44:23 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
[FATAL][2020-10-15 18:44:38 -0400]            2020/10/15 22:44:26 [error] 6#6: *194 open() "/usr/share/nginx/assets/current/500.html" failed (2: No such file or directory), client: 10.244.0.68, server: localhost, request: "GET /500.html HTTP/1.1", host: "10.244.0.37:8082"
[FATAL][2020-10-15 18:44:38 -0400]            10.244.0.68 - - [15/Oct/2020:22:44:26 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
[FATAL][2020-10-15 18:44:38 -0400]            2020/10/15 22:44:29 [error] 6#6: *195 open() "/usr/share/nginx/assets/current/500.html" failed (2: No such file or directory), client: 10.244.0.68, server: localhost, request: "GET /500.html HTTP/1.1", host: "10.244.0.37:8082"
[FATAL][2020-10-15 18:44:38 -0400]            10.244.0.68 - - [15/Oct/2020:22:44:29 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
[FATAL][2020-10-15 18:44:38 -0400]
[FATAL][2020-10-15 18:44:38 -0400]      Deployment/testapp-web: FAILED
[FATAL][2020-10-15 18:44:38 -0400]      Latest ReplicaSet: testapp-web-78567d78fb
[FATAL][2020-10-15 18:44:38 -0400]
[FATAL][2020-10-15 18:44:38 -0400]      The following containers are in a state that is unlikely to be recoverable:
[FATAL][2020-10-15 18:44:38 -0400]      > testapp-create-db: Crashing repeatedly (exit 1). See logs for more information.
[FATAL][2020-10-15 18:44:38 -0400]
[FATAL][2020-10-15 18:44:39 -0400]        - Final status: 1 replica, 1 updatedReplica, 1 unavailableReplica
[FATAL][2020-10-15 18:44:39 -0400]        - Events (common success events excluded):
[FATAL][2020-10-15 18:44:39 -0400]            [Deployment/testapp-web]        ScalingReplicaSet: Scaled up replica set testapp-web-78567d78fb to 1 (1 events)
[FATAL][2020-10-15 18:44:39 -0400]            [Pod/testapp-web-78567d78fb-nqvdd]      SuccessfulAttachVolume: AttachVolume.Attach succeeded for volume "pvc-fd6f0799-ee5b-4948-bcb3-1a9acf8c8a1d"  (1 events)
[FATAL][2020-10-15 18:44:39 -0400]            [Pod/testapp-web-78567d78fb-nqvdd]      BackOff: Back-off restarting failed container (23 events)
[FATAL][2020-10-15 18:44:39 -0400]        - Logs from container 'testapp-web': None found. Please check your usual logging service (e.g. Splunk).
[FATAL][2020-10-15 18:44:39 -0400]        - Logs from container 'testapp-migrate-db': None found. Please check your usual logging service (e.g. Splunk).
[FATAL][2020-10-15 18:44:39 -0400]        - Logs from container 'testapp-copy-assets': None found. Please check your usual logging service (e.g. Splunk).
[FATAL][2020-10-15 18:44:39 -0400]        - Logs from container 'testapp-create-db' (last 25 lines shown):
[FATAL][2020-10-15 18:44:39 -0400]            /usr/src/app/bundle/ruby/2.7.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/src/app/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/src/app/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/src/app/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/src/app/bundle/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/application.rb:339:in `require_environment!'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/src/app/bundle/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/application.rb:523:in `block in run_tasks_blocks'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/src/app/bundle/ruby/2.7.0/gems/kuby-core-0.11.4/lib/kuby/plugins/rails_app/tasks.rake:20:in `block (4 levels) in <main>'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/src/app/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
[FATAL][2020-10-15 18:44:39 -0400]            /usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
[FATAL][2020-10-15 18:44:39 -0400]            bin/bundle:113:in `load'
[FATAL][2020-10-15 18:44:39 -0400]            bin/bundle:113:in `<main>'
[FATAL][2020-10-15 18:44:39 -0400]            Tasks: TOP => environment
[FATAL][2020-10-15 18:44:39 -0400]            (See full trace by running task with --trace)
```

And here is the config:

```ruby
require 'active_support/core_ext'
require 'active_support/encrypted_configuration'

Kuby.register_package('libvips')
Kuby.register_package('libvips-dev')
Kuby.register_package('libvips-tools')
# Define a production Kuby deploy environment
Kuby.define('TestApp') do
  environment(:production) do
    # Because the Rails environment isn't always loaded when
    # your Kuby config is loaded, provide access to Rails
    # credentials manually.
    app_creds = ActiveSupport::EncryptedConfiguration.new(
      config_path: File.join('config', 'credentials.yml.enc'),
      key_path: File.join('config', 'master.key'),
      env_key: 'RAILS_MASTER_KEY',
      raise_if_missing_key: true
    )

    docker do
      # Configure your Docker registry credentials here. Add them to your
      # Rails credentials file by running `bundle exec rake credentials:edit`.
      package_phase.add('libvips')
      package_phase.add('libvips-dev')
      package_phase.add('libvips-tools')

      credentials do
        username app_creds.dig(:gitlab, :username)
        password app_creds.dig(:gitlab, :access_token)
        email app_creds.dig(:gitlab, :email)
      end

      # Configure the URL to your Docker image here, eg:
      # image_url 'foo.bar.com/me/myproject'
      #
      # If you're using Gitlab's Docker registry, try something like this:
      image_url 'registry.gitlab.com/jwald1/testapp'
    end

    kubernetes do
      # Add a plugin that facilitates deploying a Rails app.
      add_plugin :rails_app do
        # configure database credentials
        hostname "testapp.com"
        database do
          user app_creds.dig(:kuby_db, :user)
          password app_creds.dig(:kuby_db, :password)
        end
      end

      # Use Docker Desktop as the provider.
      # See: https://www.docker.com/products/docker-desktop
      #
      # Note: you will likely want to use a different provider when deploying
      # your application into a production environment. To configure a different
      # provider, add the corresponding gem to your gemfile and update the
      # following line according to the provider gem's README.
      provider :digitalocean do
        access_token app_creds.dig(:digitalocean, :access_token)
        cluster_id app_creds.dig(:digitalocean, :cluster_id)
      end
    end
  end
end
```

**Comment by camertron** [comment]
@jwald1 looks like there are two problems: 1) the Nginx assets server is failing readiness checks, and 2) the init container that tries to create your database is erroring out.

#### Assets issue
I'm not sure what's going on here. Nginx seems to be complaining that it can't find the `current` directory, which indicates the asset copy task didn't run or errored out. Try running the following command to get Kubernetes to show you some log output: `bundle exec kuby -e production kubectl -N -- logs testapp-web-78567d78fb-nqvdd -c testapp-copy-assets`.

#### Database issue
Unfortunately Krane isn't giving us enough log output so all we can see is part of a Ruby stack trace. Try running the following command to get more error info: `bundle exec kuby -e production kubectl -N -- logs testapp-web-78567d78fb-nqvdd -c testapp-create-db`.

**Comment by camertron** [comment]
Hey @jwald1, any luck getting things to work?

**Comment by jwald1** [comment]
I set up a new server and tried to deploy which failed, After running the above-suggested commands I got back `error: the server doesn't have a resource type "pods"` BTW, how do we set environment variables?

**Comment by camertron** [comment]
@jwald1 wow something is definitely not right. I've seen error messages like that from DigitalOcean when the cluster doesn't have enough resources to serve kubectl requests. Do your `kuby` commands tend to hang for a while by any chance? If that's the case, I would suggest increasing the size of one of the nodes in your node pool, or adding another node to distribute the workload. What size nodes are you using, btw? That said, I've run into a number of weird issues like this with DigitalOcean. I recently switched to Linode and have had a much better experience.

Unfortunately there's not much more I can do to debug without access to your cluster. Let me know if you'd like to hop on a call at some point :)

**Comment by jwald1** [comment]
Thanks @camertron, yes the commands hang for while... I'll give Linode a try. 
I'm currently prepending env vars to the kuby command, like so `ENV_VAR=true RAILS_MASTER_KEY=dfdsdfbdgsgetrt bundle exec kuby` is that the way to set env vars?

**Comment by camertron** [comment]
Ok cool, definitely interested to know if the switch fixes things :)

Ah sorry yeah, forgot to reply re: environment variables. Yes, prepending is the right way to go specifically for `RAILS_MASTER_KEY`. Kuby turns that env var into a kubernetes secret so it gets picked up by Rails when your app starts.

In addition, any environment variable that starts with `RAILS_` (except `RAILS_MASTER_KEY`, which is a secret) will be added to a configmap and made available to your app when it starts. For example, you could run `RAILS_SERVE_STATIC_FILES=true bundle exec kuby -e production deploy` and your app would start serving static assets without having to change any code.

I just looked through Kuby's docs and I can't believe I forgot to document how to add other env vars. There's a section on secrets which work the same way, but I definitely need to add a section dedicated specifically to non-secret env vars. For now, here's how to do it:

```ruby
Kuby.define('my-app') do
  environment(:production) do
    plugin(:rails_app) do
      config_map do
        add 'MY_ENV_VAR, ENV['MY_ENV_VAR']
      end
    end
  end
end
```

**Comment by jwald1** [comment]
Thanks, will give it a try.

**Comment by lazyatom** [comment]
It might be worth checking the logs from your database pod -- I saw errors very similar to this, and it turned out it was because the database credentials I was giving Kuby were different from the ones in `database.yml` -- it's a very strange way for that to manifest, but once I fixed it, the deploy (to a fresh cluster) worked. 🤞

**Comment by camertron** [comment]
@jwald1 I'm going to close this for now. If you have any additional info, please comment here.
