### ISSUE TITLE
Error Setting up Digital Ocean

### ISSUE THREAD

**Issue by raul-gracia** [getkuby/kuby-core#36]
```
bundle exec kuby -e production setup
```
```
Setting up kubedb
Fetching Helm chart
Error: looks like "https://charts.appscode.com/stable/" is not a valid chart repository or cannot be reached: Get https://charts.appscode.com/stable/index.yaml: dial tcp: i/o timeout
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "gitlab" chart repository (https://charts.gitlab.io):
        Get https://charts.gitlab.io/index.yaml: dial tcp: i/o timeout
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com/):
        Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp: i/o timeout
Update Complete. ⎈ Happy Helming!⎈ 
Deploying kubedb operator
Error: Kubernetes cluster unreachable
Error: failed to download "appscode/kubedb" (hint: running `helm repo update` may help)
error: could not install chart 'kubedb-operator': helm exited with status code 1
```

When I run `helm repo update` locally, it all works fine.
Here's is my config:
```ruby
require 'active_support/core_ext'
require 'active_support/encrypted_configuration'
require 'kuby/digitalocean'


# Define a production Kuby deploy environment
Kuby.define('RcruiT') do
  environment(:production) do
    # Because the Rails environment isn't always loaded when
    # your Kuby config is loaded, provide access to Rails
    # credentials manually.
    app_creds = ActiveSupport::EncryptedConfiguration.new(
      config_path: File.join('config', 'credentials.yml.enc'),
      key_path: File.join('config', 'master.key'),
      env_key: 'RAILS_MASTER_KEY',
      raise_if_missing_key: true
    )

    docker do
      # Configure your Docker registry credentials here. Add them to your
      # Rails credentials file by running `bundle exec rake credentials:edit`.
      credentials do
        username app_creds[:KUBY_DOCKER_USERNAME]
        password app_creds[:KUBY_DOCKER_PASSWORD]
        email app_creds[:KUBY_DOCKER_EMAIL]
      end

      # Configure the URL to your Docker image here, eg:
      image_url '***********'
      #
      # If you're using Gitlab's Docker registry, try something like this:
      # image_url 'registry.gitlab.com/<username>/<repo>'
    end

    kubernetes do
      # Add a plugin that facilitates deploying a Rails app.
      add_plugin :rails_app do
        # configure database credentials
        database do
          user app_creds[:KUBY_DB_USER]
          password app_creds[:KUBY_DB_PASSWORD]
        end
      end

      # Use Docker Desktop as the provider.
      # See: https://www.docker.com/products/docker-desktop
      #
      # Note: you will likely want to use a different provider when deploying
      # your application into a production environment. To configure a different
      # provider, add the corresponding gem to your gemfile and update the
      # following line according to the provider gem's README.
      # provider :docker_desktop
      provider :digitalocean do
        access_token app_creds[:DIGITAL_OCEAN_ACCESS_TOKEN]
        cluster_id '***************************'
      end

    end
  end
end
```

**Comment by camertron** [comment]
Hey @raul-gracia, this looks like potentially an issue with SSL certs on your machine. Have a look at [this issue](https://github.com/helm/helm/issues/4251) to see if any of the solutions apply to you. Some additional questions:

1. What operating system are you using?
1. Do you see the contents of the YAML file if you run `curl https://charts.appscode.com/stable/index.yaml`?
1. Are you behind a proxy?
1. Do you have a number of self-signed SSL/TLS certs installed?

**Comment by raul-gracia** [comment]
After deleting the whole helm folder with `rm -Rf ~/.helm` when I ran the `setup` command it worked successfully. 

1. I was using Mac Catalina (10.15.7)
2. I was able to see the contents both on the command line and via browser
3. I was using a VPN Service, but tried both with and without being connected
4. I don't think I have but not sure how can I double check.

The problem now is when running the command for deployment:
```
bundle exec kuby -e production deploy
```
```
error: undefined method `index' for nil:NilClass
```

I'm not sure if the `RAILS_MASTER_KEY` needs to be passed everytime when you run the command. Or what the actual content should be. 
- I've tried passing the path to the file with: `RAILS_MASTER_KEY=config/master.key bundle exec kuby -e production deploy` which returns nothing.
- And I've also tried passing the content of the file with `RAILS_MASTER_KEY=(cat config/master.key) bundle exec kuby -e production deploy` (I'm using fish shell ), which returns the above error.
- I've also tried to just hardcode the content of the master key with `RAILS_MASTER_KEY=******* bundle exec kuby -e production deploy` but same error happens.

**Comment by camertron** [comment]
@raul-gracia I've seen that undefined method error before but I can't remember what causes it. Can you run the deploy command with `GLI_DEBUG=true` and paste the stack trace in this thread?

* What do you mean by "returns nothing"? It prints no output? FYI `RAILS_MASTER_KEY` is supposed to contain the actual key, not a path to the key file.
* If config/master.key exists, there's no need to pass it in the environment. The docs say to pass it explicitly because config/master.key isn't checked into source control and may or may not exist on disk when deploys happen.
* I don't think the error you're seeing has anything to do with the master key (of course, I could be wrong).

**Comment by raul-gracia** [comment]
Looks like its related to the docker remote connection...

```bash
GLI_DEBUG=true RAILS_MASTER_KEY=******* bundle exec kuby -e production deploy
```
```ruby
error: undefined method `index' for nil:NilClass
bundler: failed to load command: kuby (/Users/maliciousmind/.rbenv/versions/2.7.1/bin/kuby)
NoMethodError: undefined method `index' for nil:NilClass
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/docker-remote-0.2.0/lib/docker/remote/client.rb:48:in `auth'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/docker-remote-0.2.0/lib/docker/remote/client.rb:20:in `tags'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.8/lib/kuby/docker/remote_tags.rb:28:in `tags'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.8/lib/kuby/docker/remote_tags.rb:39:in `timestamp_tags'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.8/lib/kuby/docker/tags.rb:68:in `timestamp_tags'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.8/lib/kuby/docker/tags.rb:73:in `latest_timestamp_tag'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.8/lib/kuby/docker/spec.rb:185:in `block in tag'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.8/lib/kuby/docker/spec.rb:184:in `fetch'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.8/lib/kuby/docker/spec.rb:184:in `tag'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.8/lib/kuby/kubernetes/spec.rb:75:in `before_deploy'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.8/lib/kuby/kubernetes/spec.rb:106:in `deploy'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.8/lib/kuby/tasks.rb:78:in `deploy'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.8/lib/kuby/commands.rb:153:in `block (2 levels) in <class:Commands>'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gli-2.19.2/lib/gli/command_support.rb:131:in `execute'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gli-2.19.2/lib/gli/app_support.rb:296:in `block in call_command'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gli-2.19.2/lib/gli/app_support.rb:309:in `call_command'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gli-2.19.2/lib/gli/app_support.rb:83:in `run'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.8/lib/kuby/commands.rb:31:in `run'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.8/bin/kuby:4:in `<top (required)>'
  /Users/maliciousmind/.rbenv/versions/2.7.1/bin/kuby:23:in `load'
  /Users/maliciousmind/.rbenv/versions/2.7.1/bin/kuby:23:in `<top (required)>'
```

**Comment by camertron** [comment]
Yeah, it looks like the response doesn't contain the `www-authenticate` header. What Docker registry are you using?

**Comment by raul-gracia** [comment]
I'm using docker hub. And when I build a push the image it works just fine.

**Comment by camertron** [comment]
Ok thanks for the info. I've never actually tried to use docker-remote with Docker Hub, so there must be something I'm missing with respect to how it works. Is your repo on Docker Hub public by any chance?

**Comment by camertron** [comment]
Ok @raul-gracia, I think the solution to this is as simple as fixing the default Docker Hub registry URL Kuby uses. It's currently using `www.docker.com` (which I thought was the correct URL), but should be using `index.docker.io`. I just pushed out a fixed version (v0.11.9) of kuby-core. Can you let me know if the new version fixes your issue?

**Comment by raul-gracia** [comment]
@camertron 

It worked!... at first. It sort of managed to connect to my cluster on DO and set up some of the replicas, etc. But, at some point, a couple of the resources got stuck, and it ended up rendering the whole cluster unreachable, even from the DO Dashboard. 
Not really knowing if it was Kuby or DO problem. I tried a couple more times creating new clusters on DO, where same thing happened. The cluster will end up being unresponsive. I tried with diff number of nodes, and diff machine types, with more memory etc. 
I've tried one more time just now. And I ended up stuck on the `setup` step once again. 
At this point I've uninstalled my local copy of `helm` and also deleted the `~/.helm` folder too.
This is the output:
```
GLI_DEBUG=true bundle exec kuby -e production setup
```
```
Setting up kubedb
Fetching Helm chart
Error: looks like "https://charts.appscode.com/stable/" is not a valid chart repository or cannot be reached: Get https://charts.appscode.com/stable/index.yaml: dial tcp: i/o timeout
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "appscode" chart repository (https://charts.appscode.com/stable/):
	Get https://charts.appscode.com/stable/index.yaml: dial tcp: i/o timeout
Update Complete. ⎈ Happy Helming!⎈
Deploying kubedb operator
Error: Kubernetes cluster unreachable
Error: failed to download "appscode/kubedb" (hint: running `helm repo update` may help)
error: could not install chart 'kubedb-operator': helm exited with status code 1
bundler: failed to load command: kuby (/Users/maliciousmind/.rbenv/versions/2.7.1/bin/kuby)
HelmCLI::InstallError: could not install chart 'kubedb-operator': helm exited with status code 1
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/helm-cli-0.3.0/lib/helm-cli.rb:61:in `install_chart'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-kube-db-0.6.0/lib/kuby/kube-db/plugin.rb:57:in `install_operator'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-kube-db-0.6.0/lib/kuby/kube-db/plugin.rb:38:in `setup'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.9/lib/kuby/kubernetes/spec.rb:97:in `block in setup'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.9/lib/kuby/trailing_hash.rb:13:in `block in each'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.9/lib/kuby/trailing_hash.rb:12:in `each'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.9/lib/kuby/trailing_hash.rb:12:in `each'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.9/lib/kuby/kubernetes/spec.rb:97:in `setup'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.9/lib/kuby/tasks.rb:21:in `setup'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.9/lib/kuby/commands.rb:137:in `block (2 levels) in <class:Commands>'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gli-2.19.2/lib/gli/command_support.rb:131:in `execute'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gli-2.19.2/lib/gli/app_support.rb:296:in `block in call_command'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gli-2.19.2/lib/gli/app_support.rb:309:in `call_command'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gli-2.19.2/lib/gli/app_support.rb:83:in `run'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.9/lib/kuby/commands.rb:31:in `run'
  /Users/maliciousmind/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/kuby-core-0.11.9/bin/kuby:4:in `<top (required)>'
  /Users/maliciousmind/.rbenv/versions/2.7.1/bin/kuby:23:in `load'
  /Users/maliciousmind/.rbenv/versions/2.7.1/bin/kuby:23:in `<top (required)>'
```
I was not using any VPN and I can visit `https://charts.appscode.com/stable/index.yaml` both on the browser and on the console via curl just fine.

**Comment by camertron** [comment]
@raul-gracia progress! Yeah I think the main issue here is Helm being weird. It looks like the same issue you mentioned earlier, and likely either a Helm bug or a problem with SSL/TLS certs on your machine :( Unfortunately the deploy won't succeed until kubedb can be installed in your cluster. Might be worth filing an issue against Helm? Kuby just tries to run `helm` commands. If they error for unusual reasons like this, there's not much I can do :( What happens if you run `helm pull appscode/kubedb`?

Yeah, the cluster unresponsiveness you mentioned is something I've seen as well and the main reason I switched from DigitalOcean to Linode. I've heard from a number of people now who have also run into this, and it makes me wonder if DO's Kubernetes offering just isn't ready yet. For what it's worth, Linode has been working flawlessly for me so far.
