### ISSUE TITLE
Fail on create-db container

### ISSUE THREAD

**Issue by vicocamacho** [getkuby/kuby-core#74]
Hi! I'm trying to setup Kuby on Digital Ocean using the following configuration:

```ruby
# We need to require some Rails stuff to read encrypted credentials
require "active_support/core_ext/hash/indifferent_access"
require "active_support/encrypted_configuration"

Kuby.define("construction") do
  environment(:production) do
    app_creds = ActiveSupport::EncryptedConfiguration.new(
      config_path: "./config/credentials/production.yml.enc",
      key_path: "./config/credentials/production.key",
      env_key: "RAILS_PRODUCTION_KEY",
      raise_if_missing_key: true
    )

    docker do
      base_image "ruby:3.0.0"
      gemfile "./Gemfile"

      webserver_phase.webserver = :puma

      credentials do
        username app_creds.dig(:digitalocean, :access_token)
        password app_creds.dig(:digitalocean, :access_token)
      end

      image_url "registry.digitalocean.com/registry/repo"
    end

    kubernetes do
      add_plugin :rails_app do
        manage_database false

        env do
          data do
            add "RAILS_LOG_TO_STDOUT", "enabled"
            add "DATABASE_URL", app_creds.dig(:mysql, :url)
          end
        end
      end

      provider :digitalocean do
        access_token app_creds.dig(:digitalocean, :access_token)
        cluster_id app_creds.dig(:digitalocean, :cluster_id)
      end
    end
  end
end
```

Everything seems to be working fine until it gets to the point of starting the application, then I get the following error, here are the  logs:

```log
[INFO][2021-12-09 03:42:30 -0600]	------------------------------------------Result: FAILURE-------------------------------------------
[FATAL][2021-12-09 03:42:30 -0600]	Successfully deployed 11 resources and failed to deploy 1 resource
[FATAL][2021-12-09 03:42:30 -0600]
[FATAL][2021-12-09 03:42:30 -0600]	Successful resources
[FATAL][2021-12-09 03:42:30 -0600]	ClusterIssuer/letsencrypt-production              Exists
[FATAL][2021-12-09 03:42:30 -0600]	ConfigMap/construction-assets-nginx-config Available
[FATAL][2021-12-09 03:42:30 -0600]	ConfigMap/construction-config             Available
[FATAL][2021-12-09 03:42:30 -0600]	Deployment/construction-assets            1 replica, 1 updatedReplica, 1 availableReplica
[FATAL][2021-12-09 03:42:30 -0600]	Ingressconstruction-ingress              Created
[FATAL][2021-12-09 03:42:30 -0600]	Secret/construction-registry-secret       Available
[FATAL][2021-12-09 03:42:30 -0600]	Secret/construction-secrets               Available
[FATAL][2021-12-09 03:42:30 -0600]	Service/construction-assets-svc           Selects at least 1 pod
[FATAL][2021-12-09 03:42:30 -0600]	Service/construction-svc                  Selects at least 1 pod
[FATAL][2021-12-09 03:42:30 -0600]	ServiceAccount/construction-assets-sa     Created
[FATAL][2021-12-09 03:42:30 -0600]	ServiceAccount/construction-sa            Created
[FATAL][2021-12-09 03:42:30 -0600]
[FATAL][2021-12-09 03:42:30 -0600]	Deployment/construction-web: FAILED
[FATAL][2021-12-09 03:42:30 -0600]	Latest ReplicaSet: construction-web-658fdfb676
[FATAL][2021-12-09 03:42:30 -0600]
[FATAL][2021-12-09 03:42:30 -0600]	The following containers are in a state that is unlikely to be recoverable:
[FATAL][2021-12-09 03:42:30 -0600]	> construction-create-db: Crashing repeatedly (exit 1). See logs for more information.
[FATAL][2021-12-09 03:42:30 -0600]
[FATAL][2021-12-09 03:42:30 -0600]	  - Final status: 1 replica, 1 updatedReplica, 1 unavailableReplica
[FATAL][2021-12-09 03:42:30 -0600]	  - Events (common success events excluded):
[FATAL][2021-12-09 03:42:30 -0600]	      [Deployment/construction-web]	ScalingReplicaSet: Scaled up replica set welcome-construction-web-658fdfb676 to 1 (1 events)
[FATAL][2021-12-09 03:42:30 -0600]	      [Pod/construction-web-658fdfb676-qvkpf]	BackOff: Back-off restarting failed container (2 events)
[FATAL][2021-12-09 03:42:30 -0600]	  - Logs from container 'construction-web': None found. Please check your usual logging service (e.g. Splunk).
[FATAL][2021-12-09 03:42:30 -0600]	  - Logs from container 'construction-migrate-db': None found. Please check your usual logging service (e.g. Splunk).
[FATAL][2021-12-09 03:42:30 -0600]	  - Logs from container 'construction-create-db':
[FATAL][2021-12-09 03:42:30 -0600]	      standard_init_linux.go:228: exec user process caused: exec format error
```

Do you have any idea of what might be causing the error? 

I don't see any connection attempts or queries on the database side of things.

Any pointers would be greatly appreciated.

Thanks!

**Comment by palkan** [comment]
Hey!

Could you please take a look at the Kubernetes dashboard and find logs for the `construction-create-db` pod.
They should shed the light on the problem (Kuby doesn't show full output here).

**Comment by kingdonb** [comment]
> exec user process caused: exec format error

Are you using an M1 mac? I got this error until I migrated my build machinery to a Linux machine that had amd64 architecture. (This really is actually the beginning and end of the whole error log, `exec format error` generally indicates a binary architecture mismatch. Logs are truncated from the top, not the bottom...)

The next issue I hit was, I wasn't setting the database password correctly.

```
- Logs from container 'construction-create-db':
```

This error output format is actually really nice also 👍 

Building on an M1 mac will only succeed if your Kubernetes cluster is also running arm64 architecture.

**Comment by vicocamacho** [comment]
@palkan I wasn't able to find any other logs. I think that's all the log information that there is available.

@kingdonb yes, I am using a M1 Mac. Since your suggestion I set up a GitHub Action to build the images on Ubuntu but encountered the following error:

```
#12 [construction-20211209032909 2/3] RUN mkdir -p /usr/share/assets
#12 0.062 standard_init_linux.go:228: exec user process caused: exec format error
#12 ERROR: process "/bin/sh -c mkdir -p /usr/share/assets" did not complete successfully: exit code: 1
------
 > [construction-20211209032909 2/3] RUN mkdir -p /usr/share/assets:
#12 0.062 standard_init_linux.go:228: exec user process caused: exec format error
------
Dockerfile:3
--------------------
   1 |     FROM registry.digitalocean.com/registry/construction:20211209032909 AS welcome-construction-20211209032909
   2 |     ARG RAILS_MASTER_KEY
   3 | >>> RUN mkdir -p /usr/share/assets
   4 |     RUN env RAILS_MASTER_KEY=$RAILS_MASTER_KEY bundle exec rake kuby:rails_app:assets:copy
   5 |     FROM registry.digitalocean.com/registry/construction:20211209165226 AS construction-20211209165226
--------------------
error: failed to solve: process "/bin/sh -c mkdir -p /usr/share/assets" did not complete successfully: exit code: 1
error: build failed: docker command exited with status code 1
```

Seems like a very similar error, just on another part of the deployment process. Do you have any idea of what I need to do to solve it?

**Comment by camertron** [comment]
@vicocamacho hmm very interesting, I haven't seen this before but it sounds plausible that it's caused by a mismatch in processor architecture as @kingdonb suggests. It makes sense then that there aren't any logs because none of the executables were able to run. Thanks to one of @palkan's recent changes, `kuby build` forwards arguments on to `docker build` now. That means you should be able to run `kuby -e production build -- --platform linux/amd64`.

It looks like the error you're seeing in GitHub actions is happening while building the assets image. I believe that `RUN mkdir` directive is the first time the Dockerfile tries to execute a binary. My guess is the app image was built on your M1 and pushed to the Docker registry, and that's what the assets image is being built from. In other words, that `mkdir` executable is the one included in registry.digitalocean.com/registry/construction:20211209032909, which was built for arm64. You'll need to delete the arm64 images from the registry and run the action again so the amd64 images are built instead.

**Comment by kingdonb** [comment]
I did run into that too. Because the assets image builds from the previous version of the assets image, you get `exec format error` on the way in and again on the way out. Deleting the original badly exec-formatted image was the way out for me.

It would be cool to build multiarch images, I wonder how hard that is going to be to add... that's going to take a little bit of time for me to answer, but I have some multiarch images that I can use as reference to compare against. (I should be able to add it?)

**Comment by camertron** [comment]
This is probably a good opportunity for Kuby to print a helpful message if you try to build on a non-x86 machine, since I have to think most people will be running their Kuby-managed Docker images on x86 hardware and not arm.

**Comment by camertron** [comment]
See: https://github.com/getkuby/kuby-core/commit/549b0b03f634a7f1e4bbb3418cc4036379e3dee8

**Comment by vicocamacho** [comment]
Thank you for your help @camertron @kingdonb with your help I was able to get the deployment working!

But right now I'm facing an issue that when I try to make another deployment it fails when it tries to copy the assets for the second time, here are the logs that I am getting:

```
#15 [construction-20211211192102 3/3] RUN env RAILS_MASTER_KEY=$RAILS_MASTER_KEY bundle exec rake kuby:rails_app:assets:copy
#15 1.351 rake aborted!
#15 1.351 ActiveSupport::MessageEncryptor::InvalidMessage: ActiveSupport::MessageEncryptor::InvalidMessage
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/message_encryptor.rb:203:in `rescue in _decrypt'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/message_encryptor.rb:180:in `_decrypt'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/message_encryptor.rb:154:in `decrypt_and_verify'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/messages/rotator.rb:22:in `decrypt_and_verify'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/encrypted_file.rb:92:in `decrypt'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/encrypted_file.rb:54:in `read'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/encrypted_configuration.rb:21:in `read'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/encrypted_configuration.rb:33:in `config'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/encrypted_configuration.rb:38:in `options'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/core_ext/module/delegation.rb:309:in `method_missing'
#15 1.351 /usr/src/app/kuby.rb:20:in `block (4 levels) in <main>'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/docker/spec.rb:139:in `instance_eval'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/docker/spec.rb:139:in `credentials'
#15 1.351 /usr/src/app/kuby.rb:19:in `block (3 levels) in <main>'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/environment.rb:16:in `instance_eval'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/environment.rb:16:in `docker'
#15 1.351 /usr/src/app/kuby.rb:14:in `block (2 levels) in <main>'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/definition.rb:28:in `instance_eval'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/definition.rb:28:in `environment'
#15 1.351 /usr/src/app/kuby.rb:6:in `block in <main>'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby.rb:51:in `instance_eval'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby.rb:51:in `define'
#15 1.351 /usr/src/app/kuby.rb:5:in `<main>'
#15 1.351 /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
#15 1.351 /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
#15 1.351 /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
#15 1.351 /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
#15 1.351 /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
#15 1.351 /usr/local/bundle/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby.rb:44:in `load!'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/plugins/rails_app/tasks.rake:30:in `block (4 levels) in <main>'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
#15 1.351 ./bin/bundle:113:in `load'
#15 1.351 ./bin/bundle:113:in `<main>'
#15 1.351 Tasks: TOP => kuby:rails_app:assets:copy
#15 1.351 (See full trace by running task with --trace)
#15 ERROR: process "/bin/sh -c env RAILS_MASTER_KEY=$RAILS_MASTER_KEY bundle exec rake kuby:rails_app:assets:copy" did not complete successfully: exit code: 1
------
 > [construction-20211211192102 3/3] RUN env RAILS_MASTER_KEY=$RAILS_MASTER_KEY bundle exec rake kuby:rails_app:assets:copy:
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
#15 1.351 ./bin/bundle:113:in `load'
#15 1.351 ./bin/bundle:113:in `<main>'
#15 1.351 Tasks: TOP => kuby:rails_app:assets:copy
#15 1.351 (See full trace by running task with --trace)
------
Dockerfile:7
--------------------
   5 |     FROM registry.digitalocean.com/registry/construction:20211211192102 AS construction-20211211192102
   6 |     COPY --from=construction-20211211021459 /usr/share/assets /usr/share/assets
   7 | >>> RUN env RAILS_MASTER_KEY=$RAILS_MASTER_KEY bundle exec rake kuby:rails_app:assets:copy
   8 |     FROM nginx:1.9-alpine
   9 |     COPY --from=construction-20211211192102 /usr/share/assets /usr/share/nginx/assets
--------------------
error: failed to solve: process "/bin/sh -c env RAILS_MASTER_KEY=$RAILS_MASTER_KEY bundle exec rake kuby:rails_app:assets:copy" did not complete successfully: exit code: 1
error: build failed: docker command exited with status code 1
```

For some reason this only fails if the registry has anything in it, if I empty what's on the registry and try the deployment again it works without an issue. Do you have any pointers of what might be causing this?

**Comment by camertron** [comment]
Hey @vicocamacho, that error is usually raised when Rails can't find config/master.key or the `RAILS_MASTER_KEY` environment variable. Did you run `RAILS_MASTER_KEY=abc123 kuby build`?

**Comment by vicocamacho** [comment]
no, but it works fine until that point, it is even able to precompile the assets and everything else. Here is a little bit more of the log so maybe it is a little bit better explained:

```
#13 [construction-20211211021459 3/3] RUN env RAILS_MASTER_KEY=*** bundle exec rake kuby:rails_app:assets:copy
#13 1.304 Linked ../20211211192650/404.html -> /usr/share/assets/current/404.html
#13 1.304 Linked ../20211211192650/422.html -> /usr/share/assets/current/422.html
#13 1.304 Linked ../20211211192650/500.html -> /usr/share/assets/current/500.html
#13 1.304 Linked ../20211211192650/apple-touch-icon-precomposed.png -> /usr/share/assets/current/apple-touch-icon-precomposed.png
#13 1.304 Linked ../20211211192650/apple-touch-icon.png -> /usr/share/assets/current/apple-touch-icon.png
#13 1.354 Linked ../20211211192650/robots.txt -> /usr/share/assets/current/robots.txt
#13 DONE 1.4s

#14 [construction-20211211192102 2/3] COPY --from=construction-20211211021459 /usr/share/assets /usr/share/assets
#14 DONE 0.1s

#15 [construction-20211211192102 3/3] RUN env RAILS_MASTER_KEY=$RAILS_MASTER_KEY bundle exec rake kuby:rails_app:assets:copy
#15 1.351 rake aborted!
#15 1.351 ActiveSupport::MessageEncryptor::InvalidMessage: ActiveSupport::MessageEncryptor::InvalidMessage
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/message_encryptor.rb:203:in `rescue in _decrypt'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/message_encryptor.rb:180:in `_decrypt'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/message_encryptor.rb:154:in `decrypt_and_verify'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/messages/rotator.rb:22:in `decrypt_and_verify'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/encrypted_file.rb:92:in `decrypt'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/encrypted_file.rb:54:in `read'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/encrypted_configuration.rb:21:in `read'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/encrypted_configuration.rb:33:in `config'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/encrypted_configuration.rb:38:in `options'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/core_ext/module/delegation.rb:309:in `method_missing'
#15 1.351 /usr/src/app/kuby.rb:20:in `block (4 levels) in <main>'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/docker/spec.rb:139:in `instance_eval'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/docker/spec.rb:139:in `credentials'
#15 1.351 /usr/src/app/kuby.rb:19:in `block (3 levels) in <main>'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/environment.rb:16:in `instance_eval'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/environment.rb:16:in `docker'
#15 1.351 /usr/src/app/kuby.rb:14:in `block (2 levels) in <main>'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/definition.rb:28:in `instance_eval'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/definition.rb:28:in `environment'
#15 1.351 /usr/src/app/kuby.rb:6:in `block in <main>'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby.rb:51:in `instance_eval'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby.rb:51:in `define'
#15 1.351 /usr/src/app/kuby.rb:5:in `<main>'
#15 1.351 /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
#15 1.351 /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
#15 1.351 /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
#15 1.351 /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
#15 1.351 /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
#15 1.351 /usr/local/bundle/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
#15 1.351 /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby.rb:44:in `load!'
#15 1.351 /usr/local/bundle/gems/kuby-core-0.14.0/lib/kuby/plugins/rails_app/tasks.rake:30:in `block (4 levels) in <main>'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
#15 1.351 ./bin/bundle:113:in `load'
#15 1.351 ./bin/bundle:113:in `<main>'
#15 1.351 Tasks: TOP => kuby:rails_app:assets:copy
#15 1.351 (See full trace by running task with --trace)
#15 ERROR: process "/bin/sh -c env RAILS_MASTER_KEY=$RAILS_MASTER_KEY bundle exec rake kuby:rails_app:assets:copy" did not complete successfully: exit code: 1
------
 > [construction-20211211192102 3/3] RUN env RAILS_MASTER_KEY=$RAILS_MASTER_KEY bundle exec rake kuby:rails_app:assets:copy:
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
#15 1.351 /usr/local/bundle/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
#15 1.351 ./bin/bundle:113:in `load'
#15 1.351 ./bin/bundle:113:in `<main>'
#15 1.351 Tasks: TOP => kuby:rails_app:assets:copy
#15 1.351 (See full trace by running task with --trace)
------
Dockerfile:7
--------------------
   5 |     FROM registry.digitalocean.com/registry/construction:20211211192102 AS construction-20211211192102
   6 |     COPY --from=construction-20211211021459 /usr/share/assets /usr/share/assets
   7 | >>> RUN env RAILS_MASTER_KEY=$RAILS_MASTER_KEY bundle exec rake kuby:rails_app:assets:copy
   8 |     FROM nginx:1.9-alpine
   9 |     COPY --from=construction-20211211192102 /usr/share/assets /usr/share/nginx/assets
--------------------
error: failed to solve: process "/bin/sh -c env RAILS_MASTER_KEY=$RAILS_MASTER_KEY bundle exec rake kuby:rails_app:assets:copy" did not complete successfully: exit code: 1
error: build failed: docker command exited with status code 1
Error: Process completed with exit code 1.
```

**Comment by camertron** [comment]
Ok, I would definitely try prefixing the `kuby build` command with `RAILS_MASTER_KEY=<key>`. You might be running into the same issue described in https://github.com/getkuby/kuby-core/pull/77, and a good workaround is to make sure that environment variable is set. Can you copy/paste the exact command you're running (omitting your actual master key of course).
